angular.module('partials', [])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/factors.html', [
'',
'<div>',
'  <div class="row-fluid">',
'    <h3 class="span12">Ingresa el objetivo de la comparación. En ocasiones es conocida como la meta.</h3>',
'    <input type="text" ng-model="parentFactor.meta" class="input-xxlarge">',
'  </div>',
'  <div ng-hide="!!parentFactor.parent" class="options">',
'    <h3>Ingrese los Proyectos/Opciones a evaluar en el objetivo.',
'      <button ng-click="addOption()" class="btn btn-primary"><i class="icon-plus icon-white"></i> Opción</button>',
'    </h3>',
'    <div class="row-fluid">',
'      <table class="table">',
'        <tr>',
'          <th></th>',
'          <th>Nombre</th>',
'        </tr>',
'        <tr ng-repeat="option in options">',
'          <td ng-bind="$index+1"></td>',
'          <td>',
'            <input type="text" ng-model="option.name">',
'          </td>',
'        </tr>',
'      </table>',
'    </div>',
'  </div>',
'  <hr>',
'  <div class="factors-table"></div>',
'  <h3>Seleccione ahora como es cada opción frente a otra basados en cada factor de decisión.</h3>',
'  <div ng-repeat="factor in factors">',
'    <div class="factor-options"></div>',
'  </div>',
'  <div ng-show="$root.show_process" class="process">',
'    <h3>Resultados de los Factores</h3>',
'    <div class="row-fluid">',
'      <table class="table table-bordered table-striped">',
'        <tr>',
'          <td></td>',
'          <th ng-repeat="factor in factors" ng-bind="factor.name"></th>',
'          <th>Totales</th>',
'        </tr>',
'        <tr>',
'          <td></td>',
'          <th ng-repeat="factor in factors" ng-bind="parentFactor.rowSum[$index]|number:2"></th>',
'          <td></td>',
'        </tr>',
'        <tr ng-repeat="option in options">',
'          <th ng-bind="option.name"></th>',
'          <td ng-repeat="factor in factors" ng-bind="parentFactor.rowSumOptions[$index][$parent.$index] | number:2"></td>',
'          <th ng-bind="(parentFactor.getOptionsScore($index)*100 | number:2) + \'%\'"></th>',
'        </tr>',
'      </table>',
'    </div>',
'  </div>',
'  <h3>Resumen</h3>',
'  <p>Para el presente ejercicio se realizó el análisis por jerarquía de procesos para lograr la meta {{parentFactor.meta}}, y el score fué el siguiente:</p>',
'  <ol>',
'    <li ng-repeat="option in options"><b ng-bind="option.name"></b>, Score:<span ng-bind="(parentFactor.getOptionsScore($index)*100|number:2) + \'%\'"></span></li>',
'  </ol>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/factors_table.html', [
'',
'<div>',
'  <h3>Cuales son los factores de decisión ?',
'    <button ng-click="addFactor()" class="btn btn-primary"><i class="icon-plus icon-white"></i> Factor</button>',
'  </h3>',
'  <div ng-show="factors.length &gt; 0" class="row-fluid">',
'    <table class="table">',
'      <tr>',
'        <th></th>',
'        <th>Nombre</th>',
'      </tr>',
'      <tr ng-repeat="factor in factors">',
'        <td ng-bind="$index + 1"></td>',
'        <td>',
'          <input type="text" ng-model="factor.name">',
'        </td>',
'      </tr>',
'    </table>',
'  </div>',
'  <h3>Seleccione que importancia tienen los factores de decisión.</h3>',
'  <h4>Esto se realiza comparándolos uno a uno.</h4>',
'  <table class="table">',
'    <tr>',
'      <th>Comparador</th>',
'      <th>Valor</th>',
'    </tr>',
'    <tbody ng-repeat="factorRow in factors">',
'      <tr ng-repeat="factorColumn in factors" ng-show="$index &gt; $parent.$index">',
'        <td ng-bind="factorRow.name + \' sobre \' + factorColumn.name "></td>',
'        <td>',
'          <select ng-options="value as fraction for (fraction, value) in fractions" ng-model="parentFactor.pairwise[$parent.$index][$index]"></select>',
'        </td>',
'      </tr>',
'    </tbody>',
'  </table>',
'  <div ng-show="$root.show_process" class="process">',
'    <h3>Comparación por pares</h3>',
'    <table class="table table-bordered table-striped">',
'      <tr>',
'        <td></td>',
'        <th ng-repeat="factorColumn in factors" ng-bind="factorColumn.name"></th>',
'      </tr>',
'      <tr ng-repeat="factorRow in factors">',
'        <td ng-bind="factorRow.name"></td>',
'        <td ng-repeat="factorColumn in factors"><span ng-bind="parentFactor.pairwise[$parent.$index][$index] | number:2 "></span></td>',
'      </tr>',
'    </table>',
'    <h3>Proceso de Normalización</h3>',
'    <h4>Fracciones</h4>',
'    <div class="row-fluid">',
'      <table class="table table-bordered table-striped">',
'        <tr>',
'          <td></td>',
'          <th ng-repeat="factorColumn in factors" ng-bind="factorColumn.name"></th>',
'        </tr>',
'        <tr ng-repeat="factorRow in factors">',
'          <th ng-bind="factorRow.name"></th>',
'          <td ng-repeat="factorColumn in factors" ng-bind="parentFactor.pairwisefractions[$parent.$index][$index] | number:2"></td>',
'        </tr>',
'        <tr>',
'          <th>Suma Columna</th>',
'          <td ng-repeat="factorColumn in factors" ng-bind="parentFactor.columnSum[$index] | number:2"></td>',
'        </tr>',
'      </table>',
'    </div>',
'    <h4>Normalización</h4>',
'    <div class="row-fluid">',
'      <table class="table table-bordered table-striped">',
'        <tr>',
'          <td></td>',
'          <th ng-repeat="factorColumn in factors" ng-bind="factorColumn.name"></th>',
'          <th>Peso</th>',
'          <th ng-show="parentFactor.parent">Peso Relativo</th>',
'        </tr>',
'        <tr ng-repeat="factorRow in factors">',
'          <td ng-bind="factorRow.name"></td>',
'          <td ng-repeat="factorColumn in factors" ng-bind="parentFactor.pairwisefractions[$parent.$index][$index]/parentFactor.columnSum[$index]  | number:2"></td>',
'          <td ng-bind="(parentFactor.rowSum[$index]*100 | number:2) + \'%\'"></td>',
'          <td ng-show="parentFactor.parent" ng-bind="(parentFactor.rowSum[$index]*parentFactor.parent.rowSum[parentFactor.parent.childs.indexOf(parentFactor)]*100 | number:2) + \'%\'"></td>',
'        </tr>',
'        <tr>',
'          <th>Suma Columna</th>',
'          <td ng-repeat="factorColumn in factors" ng-bind="parentFactor.columnSumUnit[$index] | number:2"></td>',
'          <td></td>',
'          <td ng-show="parentFactor.parent"></td>',
'        </tr>',
'      </table>',
'    </div>',
'  </div>',
'  <!-- TODO: Pending reactivate sub-factors-->',
'  <!--accordion-->',
'  <!--  accordion-group(ng-repeat="factor in factors", heading="{{level + 1 }} Nivel de Subfactores para {{factor.name}}")-->',
'  <!--    div.factors(childs="factor.childs", options="options", parent-factor="factor", level="level+1")-->',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/home.html', [
'',
'<div ng-controller="HomeCtrl">',
'  <div class="config pull-right">',
'    <div class="form-inline">',
'      <label class="checkbox">',
'        <input type="checkbox" ng-model="$root.show_process"> Mostrar Proceso',
'      </label>',
'    </div>',
'  </div>',
'  <div childs="rootFactor.childs" options="options" parent-factor="rootFactor" level="0" class="factors"></div>',
'  <h3>Resumen General</h3>',
'  <p>Para el presente ejercicio se realizó el análisis por jerarquía de procesos para lograr la meta {{meta}} el score es el siguiente:</p>',
'  <ol>',
'    <li ng-repeat="result in optionsScore | orderBy:\'score\':\'true\'"><b>{{result.option.name}}</b>, Score: {{result.score*100|number:2}}%</li>',
'  </ol>',
'  <button clicks-to=".file" class="btn import-cvs">Cargar</button>',
'  <input type="file" onchange="angular.element(this).scope().handleFileSelect(this)" ng-show="false" class="file">',
'  <button ng-click="saveFile()" class="btn">Guardar</button>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/nav.html', [
'',
'<ul class="nav">',
'  <li ng-class="getClass(\'/home\')"><a ng-href="#/home">Home</a></li>',
'  <li><a href="http://en.wikipedia.org/wiki/Analytic_hierarchy_process" target="_blank">Wiki Reference</a></li>',
'</ul>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/options.html', [
'',
'<div>',
'  <table class="table">',
'    <tr>',
'      <th>Compare sobre<span ng-bind="\' \' + factor.name"></span></th>',
'      <th>Valor</th>',
'    </tr>',
'    <tbody ng-repeat="factorRow in options">',
'      <tr ng-repeat="factorColumn in options" ng-show="$index &gt; $parent.$index">',
'        <td ng-bind="factorRow.name + \' sobre \' + factorColumn.name "></td>',
'        <td>',
'          <select ng-options="value as fraction for (fraction, value) in fractions" ng-model="parentFactor.pair_wise_options[$parent.$parent.$index][$parent.$index][$index]"></select>',
'        </td>',
'      </tr>',
'    </tbody>',
'  </table>',
'  <div ng-show="$root.show_process" class="process">',
'    <h3>Comparación por pares</h3>',
'    <table class="table table-bordered table-striped">',
'      <tr>',
'        <td></td>',
'        <th ng-repeat="factorColumn in options" ng-bind="factorColumn.name"></th>',
'      </tr>',
'      <tr ng-repeat="factorRow in options">',
'        <td ng-bind="factorRow.name"></td>',
'        <td ng-repeat="factorColumn in options"><span ng-bind="parentFactor.pair_wise_options[$parent.$parent.$index][$parent.$index][$index] | number:2 "></span></td>',
'      </tr>',
'    </table>',
'    <h3>Proceso de Normalización de las Opciones</h3>',
'    <h4>Fracciones</h4>',
'    <table class="table table-bordered table-striped">',
'      <tr>',
'        <td></td>',
'        <th ng-repeat="factorColumn in options" ng-bind="factorColumn.name"></th>',
'      </tr>',
'      <tr ng-repeat="factorRow in options">',
'        <td ng-bind="factorRow.name"></td>',
'        <td ng-repeat="factorColumn in options" ng-bind="parentFactor.pair_wise_options_fractions[$parent.$parent.$index][$parent.$index][$index] | number:2"></td>',
'      </tr>',
'      <tr>',
'        <th>Suma Columna</th>',
'        <td ng-repeat="factorColumn in options" ng-bind="parentFactor.columnSumOptions[$parent.$index][$index] | number:2 "></td>',
'      </tr>',
'    </table>',
'    <h4>Normalización</h4>',
'    <table class="table table-bordered table-striped">',
'      <tr>',
'        <td></td>',
'        <th ng-repeat="factorColumn in options" ng-bind="factorColumn.name"></th>',
'        <th>Peso</th>',
'        <th ng-show="parentFactor.parent">Peso Relativo</th>',
'      </tr>',
'      <tr ng-repeat="factorRow in options">',
'        <td ng-bind="factorRow.name"></td>',
'        <td ng-repeat="factorColumn in options" ng-bind="parentFactor.pair_wise_options_fractions[$parent.$parent.$index][$parent.$index][$index]/parentFactor.columnSumOptions[$parent.$parent.$index][$index] | number:2"></td>',
'        <td ng-bind="(parentFactor.rowSumOptions[$parent.$index][$index]*100 | number:2 ) + \'%\'"></td>',
'        <td ng-show="parentFactor.parent" ng-bind="(parentFactor.rowSumOptions[$parent.$parent.$index][$index]*parentFactor.rowSum[$parent.$index]*parentFactor.parent.rowSum[parentFactor.parent.childs.indexOf(parentFactor)]*100 | number:2) + \'%\'"></td>',
'      </tr>',
'      <tr>',
'        <th>Suma Columna</th>',
'        <td ng-repeat="factorColumn in options" ng-bind="parentFactor.columnSumUnitOptions[$parent.$index][$index] | number:2"></td>',
'        <td></td>',
'        <td ng-show="parentFactor.parent"></td>',
'      </tr>',
'    </table>',
'  </div>',
'</div>',''].join("\n"));
}]);