angular.module('partials', [])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/home.html', [
'',
'<div ng-app="ng-app">',
'  <div ng-controller="HomeCtrl">',
'    <div class="row-fluid">',
'      <h3 class="span3">Ingresa la meta',
'        <input type="text" ng-model="meta" class="input-xxlarge">',
'      </h3>',
'    </div>',
'    <div ng-include="\'/partials/factors.html\'"></div>',
'    <hr>',
'    <h3>Proyectos/Opciones a evaluar',
'      <button ng-click="addOption()" class="btn btn-primary"><i class="icon-plus icon-white"></i> Opción</button>',
'    </h3>',
'    <div class="row-fluid">',
'      <table class="table table-bordered table-striped">',
'        <tr>',
'          <th></th>',
'          <th>Nombre</th>',
'          <th>Descripción</th>',
'        </tr>',
'        <tr ng-repeat="option in options">',
'          <td>{{$index+1}}</td>',
'          <td>',
'            <input type="text" ng-model="option.name">',
'          </td>',
'          <td>',
'            <input type="text" ng-model="option.description">',
'          </td>',
'        </tr>',
'      </table>',
'    </div>',
'    <div ng-repeat="factor in factors">',
'      <h3>Comparación de proyectos/opciones por el factor <b>{{factor.name}}</b></h3>',
'      <div ng-include="\'/partials/options.html\'"></div>',
'    </div>',
'    <h2>Resultados</h2>',
'    <div class="row-fluid">',
'      <table class="table table-bordered table-striped">',
'        <tr>',
'          <td></td>',
'          <th ng-repeat="factor in factors">{{factor.name}}</th>',
'          <th>Totales</th>',
'        </tr>',
'        <tr>',
'          <td></td>',
'          <th ng-repeat="factor in factors">{{rowSum[$index]|number:2}}</th>',
'          <td></td>',
'        </tr>',
'        <tr ng-repeat="option in options">',
'          <th>{{option.name}}</th>',
'          <td ng-repeat="factor in factors">{{rowSumOptions[$index][$parent.$index] | number:2}}</td>',
'          <th>{{optionsScore[$index].score*100 | number:2}}%</th>',
'        </tr>',
'      </table>',
'    </div>',
'    <h3>Resumen</h3>',
'    <p>Para el presente ejercicio se realizó el análisis por jerarquía de procesos para lograr la meta {{meta}} el score es el siguiente:</p>',
'    <ol>',
'      <li ng-repeat="result in optionsScore | orderBy:\'score\':\'true\'"><b>{{result.option.name}}</b>, Score: {{result.score*100|number:2}}%</li>',
'    </ol>',
'  </div>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/factors.html', [
'',
'<h3>Factores de decisión',
'  <button ng-click="addFactor()" class="btn btn-primary"><i class="icon-plus icon-white"></i> Factor</button>',
'</h3>',
'<div class="row-fluid">',
'  <table class="table table-bordered table-striped">',
'    <tr>',
'      <th></th>',
'      <th>Nombre</th>',
'      <th>Descripción</th>',
'    </tr>',
'    <tr ng-repeat="factor in factors">',
'      <td>{{$index+1}}</td>',
'      <td>',
'        <input type="text" ng-model="factor.name">',
'      </td>',
'      <td>',
'        <input type="text" ng-model="factor.description">',
'      </td>',
'    </tr>',
'  </table>',
'</div>',
'<h3>Comparación por pares</h3>',
'<div class="row-fluid">',
'  <table class="table table-bordered table-striped">',
'    <tr>',
'      <td></td>',
'      <th ng-repeat="factorColumn in factors">{{factorColumn.name}}</th>',
'    </tr>',
'    <tr ng-repeat="factorRow in factors">',
'      <td>{{factorRow.name}}</td>',
'      <td ng-repeat="factorColumn in factors">',
'        <input type="text" ng-model="pairwise[$parent.$index][$index]">',
'      </td>',
'    </tr>',
'  </table>',
'</div>',
'<h3>Normalización</h3>',
'<h4>Fracciones</h4>',
'<div class="row-fluid">',
'  <table class="table table-bordered table-striped">',
'    <tr>',
'      <td></td>',
'      <th ng-repeat="factorColumn in factors">{{factorColumn.name}}</th>',
'    </tr>',
'    <tr ng-repeat="factorRow in factors">',
'      <th>{{factorRow.name}}</th>',
'      <td ng-repeat="factorColumn in factors">{{pairwisefractions[$parent.$index][$index] | number:2}}</td>',
'    </tr>',
'    <tr>',
'      <th>Suma Columna</th>',
'      <td ng-repeat="factorColumn in factors">{{columnSum[$index] | number:2}}</td>',
'    </tr>',
'  </table>',
'</div>',
'<h4>Normalización</h4>',
'<div class="row-fluid">',
'  <table class="table table-bordered table-striped">',
'    <tr>',
'      <td></td>',
'      <th ng-repeat="factorColumn in factors">{{factorColumn.name}}</th>',
'      <th>Peso</th>',
'    </tr>',
'    <tr ng-repeat="factorRow in factors">',
'      <td>{{factorRow.name}}</td>',
'      <td ng-repeat="factorColumn in factors">{{pairwisefractions[$parent.$index][$index]/columnSum[$index]  | number:2}}</td>',
'      <td>{{rowSum[$index]*100 | number:2}}%</td>',
'    </tr>',
'    <tr>',
'      <th>Suma Columna</th>',
'      <td ng-repeat="factorColumn in factors">{{columnSumUnit[$index] | number:2}}</td>',
'      <td></td>',
'    </tr>',
'  </table>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/nav.html', [
'',
'<ul class="nav">',
'  <li ng-class="getClass(\'/home\')"><a ng-href="#/home">Home</a></li>',
'  <li><a href="http://en.wikipedia.org/wiki/Analytic_hierarchy_process" target="_blank">Wiki Reference</a></li>',
'</ul>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/options.html', [
'',
'<h3>Comparación por pares</h3>',
'<table class="table table-bordered table-striped">',
'  <tr>',
'    <td></td>',
'    <th ng-repeat="factorColumn in options">{{factorColumn.name}}</th>',
'  </tr>',
'  <tr ng-repeat="factorRow in options">',
'    <td>{{factorRow.name}}</td>',
'    <td ng-repeat="factorColumn in options">',
'      <input type="text" ng-model="pair_wise_options[$parent.$parent.$index][$parent.$index][$index]">',
'    </td>',
'  </tr>',
'</table>',
'<h3>Normalización</h3>',
'<h4>Fracciones</h4>',
'<table class="table table-bordered table-striped">',
'  <tr>',
'    <td></td>',
'    <th ng-repeat="factorColumn in options">{{factorColumn.name}}</th>',
'  </tr>',
'  <tr ng-repeat="factorRow in options">',
'    <td>{{factorRow.name}}</td>',
'    <td ng-repeat="factorColumn in options">{{pair_wise_options_fractions[$parent.$parent.$index][$parent.$index][$index] | number:2 }}</td>',
'  </tr>',
'  <tr>',
'    <th>Suma Columna</th>',
'    <td ng-repeat="factorColumn in options">{{columnSumOptions[$parent.$parent.$index][$index] | number:2 }}</td>',
'  </tr>',
'</table>',
'<h4>Normalización</h4>',
'<table class="table table-bordered table-striped">',
'  <tr>',
'    <td></td>',
'    <th ng-repeat="factorColumn in options">{{factorColumn.name}}</th>',
'    <th>Peso</th>',
'  </tr>',
'  <tr ng-repeat="factorRow in options">',
'    <td>{{factorRow.name}}</td>',
'    <td ng-repeat="factorColumn in options">{{pair_wise_options_fractions[$parent.$parent.$index][$parent.$index][$index]/columnSumOptions[$parent.$parent.$index][$index] | number:2 }}</td>',
'    <td>{{rowSumOptions[$parent.$parent.$index][$index]*100 | number:2 }}%</td>',
'  </tr>',
'  <tr>',
'    <th>Suma Columna</th>',
'    <td ng-repeat="factorColumn in options">{{columnSumUnitOptions[$parent.$parent.$index][$index] | number:2 }}</td>',
'    <td></td>',
'  </tr>',
'</table>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/partial1.html', [
'',
'<p>This is the partial for view 1.</p>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/partial2.html', [
'',
'<p>This is the partial for view 2.</p>',
'<p>',
'  Showing of \'interpolate\' filter:',
'  {{ \'Current version is v%VERSION%.\' | interpolate }}',
'</p>',''].join("\n"));
}]);