angular.module('partials', [])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/factors.html', [
'',
'<div>',
'  <div class="row-fluid">',
'    <h3 class="span3">Ingresa la meta',
'      <input type="text" ng-model="parentFactor.meta" class="input-xxlarge">',
'    </h3>',
'  </div>',
'  <div ng-include="\'/partials/factors_table.html\'"></div>',
'  <hr>',
'  <div ng-hide="!!parentFactor.parent" class="options">',
'    <h3>Proyectos/Opciones a evaluar',
'      <button ng-click="addOption()" class="btn btn-primary"><i class="icon-plus icon-white"></i> Opción</button>',
'    </h3>',
'    <div class="row-fluid">',
'      <table class="table table-bordered table-striped">',
'        <tr>',
'          <th></th>',
'          <th>Nombre</th>',
'        </tr>',
'        <tr ng-repeat="option in options">',
'          <td>{{$index+1}}</td>',
'          <td>',
'            <input type="text" ng-model="option.name">',
'          </td>',
'        </tr>',
'      </table>',
'    </div>',
'  </div>',
'  <div ng-repeat="factor in factors">',
'    <h3>Comparación de proyectos/opciones por el factor <b>{{factor.name}}</b></h3>',
'    <div ng-include="\'/partials/options.html\'"></div>',
'  </div>',
'  <h2>Resultados</h2>',
'  <div class="row-fluid">',
'    <table class="table table-bordered table-striped">',
'      <tr>',
'        <td></td>',
'        <th ng-repeat="factor in factors">{{factor.name}}</th>',
'        <th>Totales</th>',
'      </tr>',
'      <tr>',
'        <td></td>',
'        <th ng-repeat="factor in factors">{{parentFactor.rowSum[$index]|number:2}}</th>',
'        <td></td>',
'      </tr>',
'      <tr ng-repeat="option in options">',
'        <th>{{option.name}}</th>',
'        <td ng-repeat="factor in factors">{{parentFactor.rowSumOptions[$index][$parent.$index] | number:2}}</td>',
'        <th>{{parentFactor.getOptionsScore($index)*100 | number:2}}%</th>',
'      </tr>',
'    </table>',
'  </div>',
'  <h3>Resumen</h3>',
'  <p>Para el presente ejercicio se realizó el análisis por jerarquía de procesos para lograr la meta {{parentFactor.meta}}, y el score fué el siguiente:</p>',
'  <ol>',
'    <li ng-repeat="option in options"><b>{{option.name}}</b>, Score: {{parentFactor.getOptionsScore($index)*100|number:2}}%</li>',
'  </ol>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/factors_table.html', [
'',
'<div>',
'  <h3>Factores de decisión',
'    <button ng-click="addFactor()" class="btn btn-primary"><i class="icon-plus icon-white"></i> Factor</button>',
'  </h3>',
'  <div ng-show="factors.length &gt; 0" class="row-fluid">',
'    <table class="table table-bordered table-striped">',
'      <tr>',
'        <th></th>',
'        <th>Nombre</th>',
'      </tr>',
'      <tr ng-repeat="factor in factors">',
'        <td>{{$index+1}}</td>',
'        <td>',
'          <input type="text" ng-model="factor.name">',
'        </td>',
'      </tr>',
'    </table>',
'  </div>',
'  <h3>Comparación por pares</h3>',
'  <div class="row-fluid">',
'    <table class="table table-bordered table-striped">',
'      <tr>',
'        <td></td>',
'        <th ng-repeat="factorColumn in factors">{{factorColumn.name}}</th>',
'      </tr>',
'      <tr ng-repeat="factorRow in factors">',
'        <td>{{factorRow.name}}</td>',
'        <td ng-repeat="factorColumn in factors">',
'          <input type="text" ng-model="parentFactor.pairwise[$parent.$index][$index]">',
'        </td>',
'      </tr>',
'    </table>',
'  </div>',
'  <h3>Normalización</h3>',
'  <h4>Fracciones</h4>',
'  <div class="row-fluid">',
'    <table class="table table-bordered table-striped">',
'      <tr>',
'        <td></td>',
'        <th ng-repeat="factorColumn in factors">{{factorColumn.name}}</th>',
'      </tr>',
'      <tr ng-repeat="factorRow in factors">',
'        <th>{{factorRow.name}}</th>',
'        <td ng-repeat="factorColumn in factors">{{parentFactor.pairwisefractions[$parent.$index][$index] | number:2}}</td>',
'      </tr>',
'      <tr>',
'        <th>Suma Columna</th>',
'        <td ng-repeat="factorColumn in factors">{{parentFactor.columnSum[$index] | number:2}}</td>',
'      </tr>',
'    </table>',
'  </div>',
'  <h4>Normalización</h4>',
'  <div class="row-fluid">',
'    <table class="table table-bordered table-striped">',
'      <tr>',
'        <td></td>',
'        <th ng-repeat="factorColumn in factors">{{factorColumn.name}}</th>',
'        <th>Peso</th>',
'        <th ng-show="parentFactor.parent">Peso Relativo</th>',
'      </tr>',
'      <tr ng-repeat="factorRow in factors">',
'        <td>{{factorRow.name}}</td>',
'        <td ng-repeat="factorColumn in factors">{{parentFactor.pairwisefractions[$parent.$index][$index]/parentFactor.columnSum[$index]  | number:2}}</td>',
'        <td>{{parentFactor.rowSum[$index]*100 | number:2}}%</td>',
'        <td ng-show="parentFactor.parent">{{parentFactor.rowSum[$index]*parentFactor.parent.rowSum[parentFactor.parent.childs.indexOf(parentFactor)]*100 | number:2}}%</td>',
'      </tr>',
'      <tr>',
'        <th>Suma Columna</th>',
'        <td ng-repeat="factorColumn in factors">{{parentFactor.columnSumUnit[$index] | number:2}}</td>',
'        <td></td>',
'        <td ng-show="parentFactor.parent"></td>',
'      </tr>',
'    </table>',
'  </div>',
'  <accordion>',
'    <accordion-group ng-repeat="factor in factors" heading="{{level + 1 }} Nivel de Subfactores para {{factor.name}}">',
'      <factors childs="factor.childs" options="options" parent-factor="factor" level="level+1"></factors>',
'    </accordion-group>',
'  </accordion>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/home.html', [
'',
'<div ng-controller="HomeCtrl">{{ waat }}',
'  <factors childs="rootFactor.childs" options="options" parent-factor="rootFactor" level="0"></factors>',
'  <h3>Resumen General</h3>',
'  <p>Para el presente ejercicio se realizó el análisis por jerarquía de procesos para lograr la meta {{meta}} el score es el siguiente:</p>',
'  <ol>',
'    <li ng-repeat="result in optionsScore | orderBy:\'score\':\'true\'"><b>{{result.option.name}}</b>, Score: {{result.score*100|number:2}}%</li>',
'  </ol>',
'  <button clicks-to=".file" class="btn import-cvs">Cargar</button>',
'  <input type="file" onchange="angular.element(this).scope().handleFileSelect(this)" ng-show="false" class="file">',
'  <button ng-click="saveFile()" class="btn">Guardar</button>',
'</div>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/nav.html', [
'',
'<ul class="nav">',
'  <li ng-class="getClass(\'/home\')"><a ng-href="#/home">Home</a></li>',
'  <li><a href="http://en.wikipedia.org/wiki/Analytic_hierarchy_process" target="_blank">Wiki Reference</a></li>',
'</ul>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/options.html', [
'',
'<h3>Comparación por pares</h3>',
'<table class="table table-bordered table-striped">',
'  <tr>',
'    <td></td>',
'    <th ng-repeat="factorColumn in options">{{factorColumn.name}}</th>',
'  </tr>',
'  <tr ng-repeat="factorRow in options">',
'    <td>{{factorRow.name}}</td>',
'    <td ng-repeat="factorColumn in options">',
'      <input type="text" ng-model="parentFactor.pair_wise_options[$parent.$parent.$index][$parent.$index][$index]">',
'    </td>',
'  </tr>',
'</table>',
'<h3>Normalización</h3>',
'<h4>Fracciones</h4>',
'<table class="table table-bordered table-striped">',
'  <tr>',
'    <td></td>',
'    <th ng-repeat="factorColumn in options">{{factorColumn.name}}</th>',
'  </tr>',
'  <tr ng-repeat="factorRow in options">',
'    <td>{{factorRow.name}}</td>',
'    <td ng-repeat="factorColumn in options">{{parentFactor.pair_wise_options_fractions[$parent.$parent.$index][$parent.$index][$index] | number:2 }}</td>',
'  </tr>',
'  <tr>',
'    <th>Suma Columna</th>',
'    <td ng-repeat="factorColumn in options">{{parentFactor.columnSumOptions[$parent.$parent.$index][$index] | number:2 }}</td>',
'  </tr>',
'</table>',
'<h4>Normalización</h4>',
'<table class="table table-bordered table-striped">',
'  <tr>',
'    <td></td>',
'    <th ng-repeat="factorColumn in options">{{factorColumn.name}}</th>',
'    <th>Peso</th>',
'    <th ng-show="parentFactor.parent">Peso Relativo</th>',
'  </tr>',
'  <tr ng-repeat="factorRow in options">',
'    <td>{{factorRow.name}}</td>',
'    <td ng-repeat="factorColumn in options">{{parentFactor.pair_wise_options_fractions[$parent.$parent.$index][$parent.$index][$index]/parentFactor.columnSumOptions[$parent.$parent.$index][$index] | number:2 }}</td>',
'    <td>{{parentFactor.rowSumOptions[$parent.$parent.$index][$index]*100 | number:2 }}%</td>',
'    <td ng-show="parentFactor.parent">{{parentFactor.rowSumOptions[$parent.$parent.$index][$index]*parentFactor.rowSum[$parent.$index]*parentFactor.parent.rowSum[parentFactor.parent.childs.indexOf(parentFactor)]*100 | number:2}}%</td>',
'  </tr>',
'  <tr>',
'    <th>Suma Columna</th>',
'    <td ng-repeat="factorColumn in options">{{parentFactor.columnSumUnitOptions[$parent.$parent.$index][$index] | number:2 }}</td>',
'    <td></td>',
'    <td ng-show="parentFactor.parent"></td>',
'  </tr>',
'</table>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/partial1.html', [
'',
'<p>This is the partial for view 1.</p>',''].join("\n"));
}])
.run(['$templateCache', function($templateCache) {
  return $templateCache.put('/partials/partial2.html', [
'',
'<p>This is the partial for view 2.</p>',
'<p>',
'  Showing of \'interpolate\' filter:',
'  {{ \'Current version is v%VERSION%.\' | interpolate }}',
'</p>',''].join("\n"));
}]);